apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "{{cookiecutter.helm_package}}.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "{{cookiecutter.helm_package}}.name" . }}
    helm.sh/chart: {{ include "{{cookiecutter.helm_package}}.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  configuration-file: |
    server.port: {{ .Values.containerPort }}
    server.log-level: {{ .Values.logLevel }}
