include:
  - project: 'milobella/devops/ci-templates'
    file: '/templates/common-template.yml'

stages:
  - build
  - release
  - deploy

variables:
  DH_REGISTRY_IMAGE: $DOCKER_USER/$CI_PROJECT_NAME
  PROJECT_NAME: "milobella"
  MODULE_NAME: ${CI_PROJECT_NAME}
  MODULE_DESCRIPTION: "{{cookiecutter.project_description}}"
  HELM_NAME: "{{cookiecutter.helm_package}}"
